# Netlify configuration file
[build]
  # Base directory of your project (where package.json is located)
  base = "."
  # Build command for Next.js
  command = "npm run build"
  # Path to the directory containing the built assets
  publish = ".netlify/build-output"

# Environment variables configuration
[build.environment]
  # Set Node version
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Next.js plugin configuration
[build.processing]
  skip_processing = false

# For the Next.js plugin
[build.processing.html]
  pretty_urls = true

# This ensures all routes are handled by Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
