# render.yaml
services:
  - type: web
    name: interview-ai-model-service
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://your-vercel-app.vercel.app
      - key: NODE_ENV
        value: production
